### ISSUE TITLE
Future cleanups and deprecations

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup-py#388]
- [ ] HTTP request cache. Used literally nowhere except JSONSchemas. For testing purposes, it would be better to implement a dummy server, since we need a WS anyway.
- [ ] Old `spec_version` migrations. It has been bumped on version 3.0 for the last time.
- [ ] TzKT `Watchdog`. Used to workaround `pysignalr` issues, currently not used anywhere.
